### ISSUE TITLE
The word `version` in `last-version` is accidentally highlighted

### ISSUE THREAD

**Issue by tom-tan** [manabuishii/language-cwl#1]
How to reproduce:

Open the following CWL snippet in Atom with language-cwl: 
```yaml
steps:
  last_stdout:
    run: last-version.cwl
    in: []
    out: [last_version_stdout]
```

Expected: `steps`, `run`, `in` and `out` are highlighted.

Actual: `steps`, `run`, `in` and `out` are highlighted. In addition to that, `version` in `last-version.cwl` is also highlighted.
